version: "3.9"

services:
  # https://hub.docker.com/r/jwilder/whoami
  whoami:
    extends:
      file: ../../common-services.yml
      service: image_base
    image: jwilder/whoami
    container_name: whoami
    hostname: whoami
