version: "3.9"

networks:
  t2_proxy:
    name: t2_proxy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true

services:
  # https://github.com/go-gitea/gitea
  gitea:
    extends:
      file: ../../common-services.yml
      service: init_with_networks
    #image: gitea/gitea:latest
    image: kunde21/gitea-arm:latest # works with raspberry pi
    container_name: gitea
    hostname: gitea
    ports:
      - ${GITEA_SSH_PORT}:22/tcp
      - ${GITEA_HTTP_PORT}:3000/tcp
    volumes:
      - ./data/gitea/data:/data:rw
    labels:
      - homepage.group=Coding
      - homepage.name=Gitea
      - homepage.icon=gitea.png
      - homepage.href=$GITEA_HOMEPAGE_URL
      - homepage.ping=$GITEA_HOMEPAGE_PING
      - homepage.description=$GITEA_HOMEPAGE_DESCRIPTION
      - homepage.hideErrors=true
      - homepage.showStats=true    
