version: "3.9"

networks:
  t2_proxy:
    name: t2_proxy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true

services:
  # https://github.com/benbusby/whoogle-search
  whoogle:
    extends:
      file: ../../common-services.yml
      service: init_with_networks
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    hostname: whoogle
    ports:
      - ${WHOOGLE_HTTP_PORT}:5000
    labels:
      - homepage.group=Other
      - homepage.name=Whoogle
      - homepage.icon=whooglesearch.png
      - homepage.href=$WHOOGLE_HOMEPAGE_URL
      - homepage.ping=$WHOOGLE_HOMEPAGE_PING
      - homepage.description=$WHOOGLE_HOMEPAGE_DESCRIPTION
      - homepage.hideErrors=true
      - homepage.showStats=true      
