version: "3.9"

networks:
  t2_proxy:
    name: t2_proxy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true

services:
  wikijs-db:
    image: postgres:11-alpine
    extends:
      file: ../../common-services.yml
      service: init_with_networks
    container_name: wikijs-db
    hostname: wikijs-db
    environment:
      POSTGRES_DB: ${WIKIJS_POSTGRES_DB}
      POSTGRES_PASSWORD: ${WIKIJS_POSTGRES_PASSWORD}
      POSTGRES_USER: ${WIKIJS_POSTGRES_USER}
    logging:
      driver: "none"
    volumes:
      - ./data/wikijs/db:/var/lib/postgresql/data

  wikijs:
    image: ghcr.io/requarks/wiki:2
    extends:
      file: ../../common-services.yml
      service: init_with_networks
    container_name: wikijs
    hostname: wikijs
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: ${WIKIJS_POSTGRES_USER}
      DB_PASS: ${WIKIJS_POSTGRES_PASSWORD}
      DB_NAME: ${WIKIJS_POSTGRES_DB}
    ports:
      - ${WIKIJS_PORT}:3000
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.wikijs-rtr.entrypoints=https"
      # - "traefik.http.routers.wikijs-rtr.rule=Host(`wiki.${DOMAINNAME_CLOUD_SERVER}`)"
      # - "traefik.http.routers.wikijs-rtr.tls=true"
      # - "traefik.http.routers.wikijs-rtr.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.wikijs-rtr.service=wikijs-svc"
      # - "traefik.http.services.wikijs-svc.loadbalancer.server.port=3000"
      - homepage.group=Collaboration
      - homepage.name=Wiki.js
      - homepage.icon=/icons/wikijs.png
      - homepage.href=$WIKIJS_HOMEPAGE_URL
      # - homepage.ping=$WIKIJS_HOMEPAGE_PING
      - homepage.description=$WIKIJS_HOMEPAGE_DESCRIPTION
      - homepage.hideErrors=true
      - homepage.showStats=false
